registration_module:
  resource: controllers/registration.yaml

login_module:
  resource: controllers/login.yaml

logout:
  path: /logout
  methods: GET

post_module:
  resource: controllers/post.yaml
  prefix: /post
  name_prefix: post_

test_module:
  resource: controllers/test.yaml
  prefix: /test
  name_prefix: test_
