index:
  path: /
  methods: GET
  controller: App\Controller\PostController::index

new:
  path: /new
  methods: GET|POST
  controller: App\Controller\PostController::new

show:
  path: /{id<\d+>}
  methods: GET
  controller: App\Controller\PostController::show

edit:
  path: /{id<\d+>}/edit
  methods: GET|POST
  controller: App\Controller\PostController::edit

delete:
  path: /{id<\d+>}
  methods: DELETE
  controller: App\Controller\PostController::delete